import { StyleSheet } from 'react-native';
import { colors } from '../theme';

export const orderFormStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 100,
    width: '100%',
    maxWidth: '95%', // Use 95% of screen width
    alignSelf: 'center',
  },
  formCard: {
    width: '100%',
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 24,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 32,
    color: colors.text,
    textAlign: 'center',
  },
  titleMobile: {
    fontSize: 24,
    marginTop: 10,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: colors.accent,
    marginTop: 32,
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: colors.border,
    paddingBottom: 12,
  },
  label: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.subText,
    marginBottom: 10,
    marginLeft: 4,
  },
  input: {
    backgroundColor: colors.bg,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 20,
    paddingVertical: 16,
    fontSize: 18,
    color: colors.text,
    marginBottom: 20,
  },
  pickerContainer: {
    backgroundColor: colors.bg,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 20,
    overflow: 'hidden',
  },
  picker: {
    height: 60,
    width: '100%',
    color: colors.text,
    backgroundColor: colors.bg,
  },
  addProductBtn: {
    backgroundColor: 'rgba(0, 188, 212, 0.1)', // colors.accent with opacity
    paddingVertical: 18,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 20,
    width: '100%',
    borderWidth: 1,
    borderColor: colors.accent,
    borderStyle: 'dashed',
  },
  addProductBtnText: {
    color: colors.accent,
    fontWeight: '600',
    fontSize: 18,
  },
  createOrderBtn: {
    backgroundColor: colors.accent,
    paddingVertical: 20,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 32,
    width: '100%',
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  createOrderBtnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 20,
    textTransform: 'uppercase',
  },
  success: {
    color: colors.success,
    marginTop: 20,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(76, 175, 80, 0.3)',
  },
  error: {
    color: colors.danger,
    marginTop: 20,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
    backgroundColor: 'rgba(239, 83, 80, 0.1)',
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(239, 83, 80, 0.3)',
  },
  fullWidth: {
    width: '100%',
  },
});
