-- Tabla: facturas_ventas
CREATE TABLE IF NOT EXISTS facturas_ventas (
  factura_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cliente_nombre text,
  descripcion text,
  fecha_factura timestamptz DEFAULT now(),
  estado text DEFAULT 'pendiente',
  metodo text,
  total numeric
);

-- Tabla: ordenes
CREATE TABLE IF NOT EXISTS ordenes (
  orden_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  factura_id integer,
  tipo_pedido text DEFAULT 'mesa'::text,
  estado_orden text DEFAULT 'pendiente'::text,
  fecha_orden timestamptz DEFAULT now()
);

-- Tabla: domicilios
CREATE TABLE IF NOT EXISTS domicilios (
  domicilio_id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  fecha_creado timestamptz,
  factura_id integer,
  orden_id integer,
  telefono text,
  telefono_domiciliario_asignado text,
  direccion_entrega text,
  costo_domicilio numeric DEFAULT 0,
  estado_domicilio text DEFAULT 'pendiente'::text
);

-- Tabla: clientes
CREATE TABLE IF NOT EXISTS clientes (
  telefono text PRIMARY KEY,
  direccion_dos text,
  direccion text,
  cliente_nombre text,
  direccion_tres text
);

-- Tabla: productos
CREATE TABLE IF NOT EXISTS productos (
  producto_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  producto_nombre text UNIQUE NOT NULL,
  categoria text DEFAULT 'Otros',
  descripcion text,
  activo boolean DEFAULT true
);

-- Tabla: producto_variantes
CREATE TABLE IF NOT EXISTS producto_variantes (
  variante_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  producto_id integer NOT NULL,
  nombre text NOT NULL,
  precio numeric NOT NULL,
  descripcion text,
  activo boolean DEFAULT true
);

-- Tabla: pizza_sabores
CREATE TABLE IF NOT EXISTS pizza_sabores (
  sabor_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre text UNIQUE NOT NULL,
  tipo text DEFAULT 'tradicional',
  recargo_pequena numeric DEFAULT 0,
  recargo_mediana numeric DEFAULT 0,
  recargo_grande numeric DEFAULT 0,
  activo boolean DEFAULT true
);

-- Tabla: ordenes_productos
CREATE TABLE IF NOT EXISTS ordenes_productos (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  orden_id integer,
  producto text,
  cantidad numeric CHECK (cantidad >= 0::numeric),
  precio_unitario numeric,
  variante_id integer
);

-- Tabla: domiciliarios
CREATE TABLE IF NOT EXISTS domiciliarios (
  telefono text PRIMARY KEY,
  domiciliario_nombre text
);

-- Tabla: facturas_pagos
CREATE TABLE IF NOT EXISTS facturas_pagos (
  pagos_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  total numeric,
  nombre_gasto text,
  descripcion text,
  estado text,
  fecha_factura date,
  metodo text
);

-- Constraints FOREIGN KEY (añadidas según las referencias detectadas)
ALTER TABLE IF EXISTS domicilios
  ADD CONSTRAINT domicilios_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES facturas_ventas(factura_id);

ALTER TABLE IF EXISTS ordenes
  ADD CONSTRAINT ordenes_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES facturas_ventas(factura_id);

ALTER TABLE IF EXISTS domicilios
  ADD CONSTRAINT domicilios_orden_id_fkey FOREIGN KEY (orden_id) REFERENCES ordenes(orden_id);

ALTER TABLE IF EXISTS ordenes_productos
  ADD CONSTRAINT ordenes_productos_orden_id_fkey FOREIGN KEY (orden_id) REFERENCES ordenes(orden_id);

ALTER TABLE IF EXISTS producto_variantes
  ADD CONSTRAINT producto_variantes_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES productos(producto_id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS ordenes_productos
  ADD CONSTRAINT ordenes_productos_variante_id_fkey FOREIGN KEY (variante_id) REFERENCES producto_variantes(variante_id);

ALTER TABLE IF EXISTS domicilios
  ADD CONSTRAINT domicilios_telefono_fkey FOREIGN KEY (telefono) REFERENCES clientes(telefono);

ALTER TABLE IF EXISTS domicilios
  ADD CONSTRAINT domicilios_telefono_domiciliario_asignado_fkey FOREIGN KEY (telefono_domiciliario_asignado) REFERENCES domiciliarios(telefono);

-- Tabla: users (for auth)
CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  username text UNIQUE NOT NULL,
  name text,
  passwordHash text NOT NULL,
  roles text[] DEFAULT '{}',
  createdAt timestamptz DEFAULT now(),
  updatedAt timestamptz DEFAULT now()
);