w-- Tabla: facturas_ventas
CREATE TABLE IF NOT EXISTS facturas_ventas (
  factura_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cliente_nombre text,
  descripcion text,
  fecha_factura timestamptz DEFAULT now(),
  estado text DEFAULT 'pendiente',
  metodo text,
  total numeric
);

-- Tabla: ordenes
CREATE TABLE IF NOT EXISTS ordenes (
  orden_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  factura_id integer,
  tipo_pedido text DEFAULT 'mesa'::text,
  estado_orden text DEFAULT 'pendiente'::text,
  fecha_orden timestamptz DEFAULT now()
);

-- Tabla: domicilios
CREATE TABLE IF NOT EXISTS domicilios (
  domicilio_id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  fecha_creado timestamptz,
  factura_id integer,
  orden_id integer,
  telefono text,
  telefono_domiciliario_asignado text,
  estado_domicilio text DEFAULT 'pendiente'::text
);

-- Tabla: clientes
CREATE TABLE IF NOT EXISTS clientes (
  telefono text PRIMARY KEY,
  direccion_dos text,
  direccion text,
  cliente_nombre text,
  direccion_tres text
);

-- Tabla: ordenes_productos
CREATE TABLE IF NOT EXISTS ordenes_productos (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  orden_id integer,
  producto text,
  cantidad numeric CHECK (cantidad >= 0::numeric)
);

-- Tabla: productos
CREATE TABLE IF NOT EXISTS productos (
  producto_nombre text PRIMARY KEY,
  precio numeric
);

-- Tabla: domiciliarios
CREATE TABLE IF NOT EXISTS domiciliarios (
  telefono text PRIMARY KEY,
  domiciliario_nombre text
);

-- Tabla: facturas_pagos
CREATE TABLE IF NOT EXISTS facturas_pagos (
  pagos_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  total numeric,
  nombre_gasto text,
  descripcion text,
  estado text,
  fecha_factura date,
  metodo text
);

-- Constraints FOREIGN KEY (añadidas según las referencias detectadas)
ALTER TABLE IF EXISTS domicilios
  ADD CONSTRAINT domicilios_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES facturas_ventas(factura_id);

ALTER TABLE IF EXISTS ordenes
  ADD CONSTRAINT ordenes_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES facturas_ventas(factura_id);

ALTER TABLE IF EXISTS domicilios
  ADD CONSTRAINT domicilios_orden_id_fkey FOREIGN KEY (orden_id) REFERENCES ordenes(orden_id);

ALTER TABLE IF EXISTS ordenes_productos
  ADD CONSTRAINT ordenes_productos_orden_id_fkey FOREIGN KEY (orden_id) REFERENCES ordenes(orden_id);

ALTER TABLE IF EXISTS ordenes_productos
  ADD CONSTRAINT ordenes_productos_producto_fkey FOREIGN KEY (producto) REFERENCES productos(producto_nombre);

ALTER TABLE IF EXISTS domicilios
  ADD CONSTRAINT domicilios_telefono_fkey FOREIGN KEY (telefono) REFERENCES clientes(telefono);

ALTER TABLE IF EXISTS domicilios
  ADD CONSTRAINT domicilios_telefono_domiciliario_asignado_fkey FOREIGN KEY (telefono_domiciliario_asignado) REFERENCES domiciliarios(telefono);

-- Tabla: users (for auth)
CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  username text UNIQUE NOT NULL,
  name text,
  passwordHash text NOT NULL,
  roles text[] DEFAULT '{}',
  createdAt timestamptz DEFAULT now(),
  updatedAt timestamptz DEFAULT now()
);