import { StyleSheet } from 'react-native';
import { colors } from './theme';

export const navbarStyles = StyleSheet.create({
  menuBtnContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 200,
    backgroundColor: 'transparent',
    padding: 12,
  },
  menuBtn: {
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  menuBtnText: {
    color: colors.text,
    fontSize: 24,
    fontWeight: 'bold',
  },
  drawerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 99,
  },
  navbar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.card,
    borderBottomWidth: 2,
    borderBottomColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  sidebarMobile: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 260,
    backgroundColor: colors.card,
    zIndex: 100,
    height: '100%',
    paddingTop: 60,
    paddingBottom: 20,
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    borderRightWidth: 2,
    borderRightColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  sidebarBtnMobile: {
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
    alignItems: 'flex-start',
  },
  link: {
    fontSize: 16,
    color: colors.text,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  linkActive: {
    color: colors.primary,
    fontWeight: 'bold',
  },
});
