import { StyleSheet } from 'react-native';
import { colors } from '../theme';

export const orderStyles = StyleSheet.create({
  container: { flex: 1, padding: 16, backgroundColor: colors.bg },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 18,
    color: colors.text,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  titleMobile: {
    paddingTop: 38,
  },
  text: { color: colors.text, fontSize: 16 },
  filterRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 16 },
  filterBtn: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 999, borderWidth: 1, borderColor: colors.accent },
  filterBtnActive: { backgroundColor: colors.accent },
  filterText: { color: colors.accent, fontWeight: 'bold', fontSize: 16 },
  filterTextActive: { color: 'white' },
  refreshBtn: { marginLeft: 'auto', backgroundColor: colors.accent, paddingVertical: 8, paddingHorizontal: 16, borderRadius: 999 },
  gridItem: { flex: 1, margin: 6, minWidth: 280, maxWidth: '33%' },
  orderBox: {
    backgroundColor: colors.card,
    padding: 18,
    borderRadius: 12,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  orderHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  orderClient: { fontWeight: 'bold', fontSize: 18, color: colors.text },
  orderInfo: { color: colors.subText, fontSize: 15, marginBottom: 2 },
  productList: { marginTop: 10, marginBottom: 8 },
  productItem: { color: colors.text, fontSize: 15, marginLeft: 12 },
  completeBtn: { backgroundColor: colors.accent, padding: 12, borderRadius: 10, marginTop: 10, alignItems: 'center' },
  completeBtnText: { color: 'white', fontWeight: 'bold', fontSize: 16, letterSpacing: 1 },
  error: { color: colors.danger, marginTop: 16, textAlign: 'center' },
});
