import { StyleSheet } from 'react-native';
import { colors } from '../components/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 100,
    width: '100%',
    maxWidth: 900,
    alignSelf: 'center',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 24,
    color: colors.text,
    textAlign: 'center',
  },
  searchContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
    alignItems: 'flex-end',
    backgroundColor: colors.card,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  inputGroup: {
    flexGrow: 1,
    minWidth: 200,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.subText,
    marginBottom: 8,
    marginLeft: 4,
  },
  input: {
    backgroundColor: colors.bg,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.text,
  },
  searchButton: {
    backgroundColor: colors.accent,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  refreshButton: {
    backgroundColor: colors.success,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.success,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  errorText: {
    color: colors.danger,
    marginBottom: 16,
    textAlign: 'center',
    fontWeight: 'bold',
    backgroundColor: 'rgba(239, 83, 80, 0.1)',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(239, 83, 80, 0.3)',
  },
  resultCard: {
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: 'rgba(0, 188, 212, 0.05)',
    padding: 16,
    borderRadius: 12,
    marginBottom: 24,
  },
  resultTitle: {
    fontWeight: 'bold',
    fontSize: 18,
    color: colors.accent,
    marginBottom: 8,
  },
  resultText: {
    fontSize: 16,
    color: colors.text,
    marginBottom: 4,
  },
  listContainer: {
    paddingBottom: 20,
  },
  clientCard: {
    backgroundColor: colors.card,
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  clientName: {
    fontWeight: 'bold',
    fontSize: 18,
    color: colors.text,
    marginBottom: 4,
  },
  clientPhone: {
    fontSize: 14,
    color: colors.subText,
    marginBottom: 2,
  },
  clientAddress: {
    fontSize: 14,
    color: colors.subText,
    marginTop: 4,
  },
  emptyText: {
    textAlign: 'center',
    color: colors.subText,
    marginTop: 32,
    fontSize: 16,
  },
  loader: {
    marginTop: 40,
  },
});
