import { StyleSheet } from 'react-native';
import { colors } from './theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  loader: {
    marginTop: 50,
  },
  errorText: {
    color: colors.danger,
    fontSize: 16,
    textAlign: 'center',
    margin: 20,
    backgroundColor: colors.dangerLight,
    padding: 10,
    borderRadius: 8,
  },
  header: {
    backgroundColor: colors.card,
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.text,
    letterSpacing: -0.5,
  },
  backButton: {
    backgroundColor: colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  backButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
    textTransform: 'uppercase',
  },
  section: {
    backgroundColor: colors.card,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.primary,
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: colors.border,
    paddingBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: 12,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  label: {
    fontWeight: '600',
    color: colors.textSecondary,
    marginRight: 12,
    minWidth: 140,
    fontSize: 16,
  },
  value: {
    color: colors.text,
    flex: 1,
    fontSize: 16,
    fontWeight: '500',
  },
  estadoValue: {
    fontWeight: 'bold',
    color: colors.success,
    backgroundColor: colors.successLight,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    overflow: 'hidden',
    alignSelf: 'flex-start',
  },
  productCard: {
    backgroundColor: colors.bg,
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  productHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 8,
  },
  productTipo: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  productCantidad: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.secondary,
    backgroundColor: colors.secondaryLight,
    paddingHorizontal: 12,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: 'hidden',
  },
  productDetail: {
    fontSize: 15,
    color: colors.textSecondary,
    marginBottom: 4,
    fontStyle: 'italic',
  },
  productPrecio: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.success,
    marginTop: 8,
    alignSelf: 'flex-end',
  },
  totalSection: {
    backgroundColor: colors.card,
    marginHorizontal: 16,
    marginBottom: 32,
    padding: 24,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.primary,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  totalLabel: {
    fontSize: 24,
    fontWeight: 'bold',
    color: colors.text,
  },
  totalValue: {
    fontSize: 32,
    fontWeight: '800',
    color: colors.primary,
  },
});
